// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createNewsStmt, err = db.PrepareContext(ctx, createNews); err != nil {
		return nil, fmt.Errorf("error preparing query CreateNews: %w", err)
	}
	if q.createTableNewsStmt, err = db.PrepareContext(ctx, createTableNews); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTableNews: %w", err)
	}
	if q.getAllNewsStmt, err = db.PrepareContext(ctx, getAllNews); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllNews: %w", err)
	}
	if q.getNewsByTitleStmt, err = db.PrepareContext(ctx, getNewsByTitle); err != nil {
		return nil, fmt.Errorf("error preparing query GetNewsByTitle: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createNewsStmt != nil {
		if cerr := q.createNewsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNewsStmt: %w", cerr)
		}
	}
	if q.createTableNewsStmt != nil {
		if cerr := q.createTableNewsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTableNewsStmt: %w", cerr)
		}
	}
	if q.getAllNewsStmt != nil {
		if cerr := q.getAllNewsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllNewsStmt: %w", cerr)
		}
	}
	if q.getNewsByTitleStmt != nil {
		if cerr := q.getNewsByTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNewsByTitleStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                  DBTX
	tx                  *sql.Tx
	createNewsStmt      *sql.Stmt
	createTableNewsStmt *sql.Stmt
	getAllNewsStmt      *sql.Stmt
	getNewsByTitleStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                  tx,
		tx:                  tx,
		createNewsStmt:      q.createNewsStmt,
		createTableNewsStmt: q.createTableNewsStmt,
		getAllNewsStmt:      q.getAllNewsStmt,
		getNewsByTitleStmt:  q.getNewsByTitleStmt,
	}
}
