// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type News struct {
	ID        int64
	Title     string
	NewsUrl   string
	ImageUrl  string
	CreatedOn string
}
