// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type News struct {
	ID        int64
	Title     string
	NewsUrl   sql.NullString
	ImageUrl  sql.NullString
	CreatedOn sql.NullString
}
