// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: news.sql

package database

import (
	"context"
)

const createNews = `-- name: CreateNews :exec
INSERT INTO news (
                  slug,
                  title,
                  news_url,
                  image_url
)
VALUES (?, ?, ?, ?)
`

type CreateNewsParams struct {
	Slug     string
	Title    string
	NewsUrl  string
	ImageUrl string
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) error {
	_, err := q.exec(ctx, q.createNewsStmt, createNews,
		arg.Slug,
		arg.Title,
		arg.NewsUrl,
		arg.ImageUrl,
	)
	return err
}

const createTableNews = `-- name: CreateTableNews :exec
CREATE TABLE IF NOT EXISTS news (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    news_url TEXT NOT NULL,
    image_url TEXT NOT NULL,
    slug TEXT NOT NULL,
    created_on TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateTableNews(ctx context.Context) error {
	_, err := q.exec(ctx, q.createTableNewsStmt, createTableNews)
	return err
}

const getAllNews = `-- name: GetAllNews :many
SELECT id, title, news_url, image_url, slug, created_on FROM news
`

func (q *Queries) GetAllNews(ctx context.Context) ([]News, error) {
	rows, err := q.query(ctx, q.getAllNewsStmt, getAllNews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []News
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.NewsUrl,
			&i.ImageUrl,
			&i.Slug,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsByTitle = `-- name: GetNewsByTitle :many
SELECT id, title, news_url, image_url, slug, created_on FROM news where INSTR(title, ?) > 0
`

func (q *Queries) GetNewsByTitle(ctx context.Context, instr string) ([]News, error) {
	rows, err := q.query(ctx, q.getNewsByTitleStmt, getNewsByTitle, instr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []News
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.NewsUrl,
			&i.ImageUrl,
			&i.Slug,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
