// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: news.sql

package database

import (
	"context"
	"database/sql"
)

const createNews = `-- name: CreateNews :exec
INSERT INTO news (
                  title,
                  news_url,
                  image_url
)
VALUES (?, ?, ?)
`

type CreateNewsParams struct {
	Title    string
	NewsUrl  sql.NullString
	ImageUrl sql.NullString
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) error {
	_, err := q.exec(ctx, q.createNewsStmt, createNews, arg.Title, arg.NewsUrl, arg.ImageUrl)
	return err
}

const getAllNews = `-- name: GetAllNews :many
SELECT id, title, news_url, image_url, created_on FROM news
`

func (q *Queries) GetAllNews(ctx context.Context) ([]News, error) {
	rows, err := q.query(ctx, q.getAllNewsStmt, getAllNews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []News
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.NewsUrl,
			&i.ImageUrl,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsByTitle = `-- name: GetNewsByTitle :many
SELECT id, title, news_url, image_url, created_on FROM news where INSTR(title, ?) > 0
`

func (q *Queries) GetNewsByTitle(ctx context.Context, instr string) ([]News, error) {
	rows, err := q.query(ctx, q.getNewsByTitleStmt, getNewsByTitle, instr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []News
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.NewsUrl,
			&i.ImageUrl,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
